## 딥러닝 활용 (2) 
### : 자연어 처리(NLP:Natural Language Processing)

In [1]:
# 자연어 처리 라이브러리 사용해보기
from tensorflow.keras.preprocessing.text import text_to_word_sequence

#1
#전처리할 텍스트 정하기
text = '해보지 않으면 해낼 수 없다'
#해당 텍스트 토큰화
result = text_to_word_sequence(text)
print("원문:",text)
print("토큰화:",result)

원문: 해보지 않으면 해낼 수 없다
토큰화: ['해보지', '않으면', '해낼', '수', '없다']


In [5]:
#2
#텍스트 전처리 함수 Tokenizer()호출
from keras.preprocessing.text import Tokenizer

#전처리할 세 개의 문장
docs = ['먼저 텍스트의 각 단어를 나누어 토큰화 합니다.','텍스트의 단어로 토큰화 해야 딥러닝에서 인식됩니다.','토큰화한 결과는 딥러닝에서 사용할 수 있습니다.']

#토큰화 함수를 이용해 전처리하는 과정
token = Tokenizer() #토큰화 함수 지정
token.fit_on_texts(docs) #토큰화 함수에 문장 적용하기

print('단어 카운트:',token.word_counts)

print('\n문장 카운트:\n',token.document_count)
print('\n각 단어가 몇 개의 문장에 포함되어 있는가:\n',token.word_docs)
print('\n각 단어에 매겨진 인덱스 값;\n', token.word_index)

단어 카운트: OrderedDict([('먼저', 1), ('텍스트의', 2), ('각', 1), ('단어를', 1), ('나누어', 1), ('토큰화', 2), ('합니다', 1), ('단어로', 1), ('해야', 1), ('딥러닝에서', 2), ('인식됩니다', 1), ('토큰화한', 1), ('결과는', 1), ('사용할', 1), ('수', 1), ('있습니다', 1)])

문장 카운트:
 3

각 단어가 몇 개의 문장에 포함되어 있는가:
 defaultdict(<class 'int'>, {'단어를': 1, '합니다': 1, '먼저': 1, '각': 1, '토큰화': 2, '나누어': 1, '텍스트의': 2, '인식됩니다': 1, '단어로': 1, '딥러닝에서': 2, '해야': 1, '수': 1, '있습니다': 1, '결과는': 1, '사용할': 1, '토큰화한': 1})

각 단어에 매겨진 인덱스 값;
 {'텍스트의': 1, '토큰화': 2, '딥러닝에서': 3, '먼저': 4, '각': 5, '단어를': 6, '나누어': 7, '합니다': 8, '단어로': 9, '해야': 10, '인식됩니다': 11, '토큰화한': 12, '결과는': 13, '사용할': 14, '수': 15, '있습니다': 16}


단어의 원-핫 인코딩
: 먼저 토큰화 함수를 불러와 단어 단위로 토큰화 하고, 각 단어의 인덱스값을 출려해보자

In [8]:
from tensorflow.keras.preprocessing.text import Tokenizer

text="오랫동안 꿈구는 이는 그 꿈을 닮아간다"

token = Tokenizer()
token.fit_on_texts([text])
print(token.word_index)

{'오랫동안': 1, '꿈구는': 2, '이는': 3, '그': 4, '꿈을': 5, '닮아간다': 6}


In [10]:
x = token.texts_to_sequences([text])
print(x)

[[1, 2, 3, 4, 5, 6]]


In [14]:
from keras.utils import to_categorical

#인덱스 수에 하나를 추가해서 원-핫 인코딩 배열 만들기
word_size = len(token.word_index) + 1
x = to_categorical(x, num_classes = word_size)

print(x)

[[[[[[1. 0. 0. ... 0. 0. 0.]
     [0. 1. 0. ... 0. 0. 0.]
     [1. 0. 0. ... 0. 0. 0.]
     ...
     [1. 0. 0. ... 0. 0. 0.]
     [1. 0. 0. ... 0. 0. 0.]
     [1. 0. 0. ... 0. 0. 0.]]

    [[0. 1. 0. ... 0. 0. 0.]
     [1. 0. 0. ... 0. 0. 0.]
     [1. 0. 0. ... 0. 0. 0.]
     ...
     [1. 0. 0. ... 0. 0. 0.]
     [1. 0. 0. ... 0. 0. 0.]
     [1. 0. 0. ... 0. 0. 0.]]

    [[0. 1. 0. ... 0. 0. 0.]
     [1. 0. 0. ... 0. 0. 0.]
     [1. 0. 0. ... 0. 0. 0.]
     ...
     [1. 0. 0. ... 0. 0. 0.]
     [1. 0. 0. ... 0. 0. 0.]
     [1. 0. 0. ... 0. 0. 0.]]

    ...

    [[0. 1. 0. ... 0. 0. 0.]
     [1. 0. 0. ... 0. 0. 0.]
     [1. 0. 0. ... 0. 0. 0.]
     ...
     [1. 0. 0. ... 0. 0. 0.]
     [1. 0. 0. ... 0. 0. 0.]
     [1. 0. 0. ... 0. 0. 0.]]

    [[0. 1. 0. ... 0. 0. 0.]
     [1. 0. 0. ... 0. 0. 0.]
     [1. 0. 0. ... 0. 0. 0.]
     ...
     [1. 0. 0. ... 0. 0. 0.]
     [1. 0. 0. ... 0. 0. 0.]
     [1. 0. 0. ... 0. 0. 0.]]

    [[0. 1. 0. ... 0. 0. 0.]
     [1. 0. 0. ... 0. 0. 0.]
     [1.

### NLP실습: 텍스트를 읽고 긍정, 부정 예측하기

In [18]:
import numpy as np
from numpy import array

#리뷰 자료 지정
docs = ['너무 재밌네요', '최고예요',' 참 잘만든 영화예요','추천하고 싶은 영화입니다', '한 번 더 보고싶네요','글쎄요','별로예요','생각보다 지루하네요','연기가 어색해요','재미없어요']

#긍정 리뷰는 1, 부정 리뷰는 0으로 클래스 지정
classes = array([1,1,1,1,1,0,0,0,0,0])

#토큰화
token = Tokenizer()
token.fit_on_texts(docs)
print(token.word_index)

{'너무': 1, '재밌네요': 2, '최고예요': 3, '참': 4, '잘만든': 5, '영화예요': 6, '추천하고': 7, '싶은': 8, '영화입니다': 9, '한': 10, '번': 11, '더': 12, '보고싶네요': 13, '글쎄요': 14, '별로예요': 15, '생각보다': 16, '지루하네요': 17, '연기가': 18, '어색해요': 19, '재미없어요': 20}


In [19]:
#토큰에 지정된 인덱스로 새로운 배열을 생성
x = token.texts_to_sequences(docs)
print(x)

[[1, 2], [3], [4, 5, 6], [7, 8, 9], [10, 11, 12, 13], [14], [15], [16, 17], [18, 19], [20]]


In [21]:
#각 학습데이터 길이를 같게 해주기 -> '패딩'과정

from tensorflow.keras.preprocessing.sequence import pad_sequences 

padded_x = pad_sequences(x,4)
print(padded_x)

[[ 0  0  1  2]
 [ 0  0  0  3]
 [ 0  4  5  6]
 [ 0  7  8  9]
 [10 11 12 13]
 [ 0  0  0 14]
 [ 0  0  0 15]
 [ 0  0 16 17]
 [ 0  0 18 19]
 [ 0  0  0 20]]


- 원-핫 인코딩으로 만들어진 고차원 벡터를 '임베딩'을 토해 밀집된 정보로 만들어줌

- 즉, 단어간의 유사도를 고려해 각 배열을 새로운 수치로!
- by Embedding(몇개의 단어들에서, 몇개의 출력 노드로, 몇개씩 인풋)

In [28]:
#임베딩 층 만들기
# 필요한 파라미터: 1. 입력, 2. 출력, 3. 단어수 : 총 몇개의 집합에서, 몇 개의 임베딩 결과를 사용할 것인지 그리고 매번 입력될 단어 수는 몇 개

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,Dense, Flatten

word_size = len(token.word_index)+1

model = Sequential()
model.add(Embedding(word_size, 8, input_length=4))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
model.fit(padded_x, classes, epochs=20)

print("\n accuracy: %.4f"%(model.evaluate(padded_x, classes)[1]))

Epoch 1/20
1/1 [==============================] - 0s 3ms/step - loss: 0.6930 - accuracy: 0.6000
Epoch 2/20
1/1 [==============================] - 0s 3ms/step - loss: 0.6910 - accuracy: 0.6000
Epoch 3/20
1/1 [==============================] - 0s 3ms/step - loss: 0.6890 - accuracy: 0.7000
Epoch 4/20
1/1 [==============================] - 0s 2ms/step - loss: 0.6870 - accuracy: 0.7000
Epoch 5/20
1/1 [==============================] - 0s 3ms/step - loss: 0.6850 - accuracy: 0.7000
Epoch 6/20
1/1 [==============================] - 0s 2ms/step - loss: 0.6831 - accuracy: 0.7000
Epoch 7/20
1/1 [==============================] - 0s 991us/step - loss: 0.6811 - accuracy: 0.8000
Epoch 8/20
1/1 [==============================] - 0s 4ms/step - loss: 0.6791 - accuracy: 0.8000
Epoch 9/20
1/1 [==============================] - 0s 2ms/step - loss: 0.6771 - accuracy: 0.8000
Epoch 10/20
1/1 [==============================] - 0s 2ms/step - loss: 0.6752 - accuracy: 0.8000
Epoch 11/20
1/1 [====================